"""add receipt line item columns

Revision ID: 0aa7d9ccca1a
Revises: bac998d15202
Create Date: 2026-08-31 01:51:26.961701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa7d9ccca1a'
down_revision = 'bac998d15202'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_line_items', sa.Column('receipt_id', sa.Uuid(), nullable=False))
    op.add_column('receipt_line_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_receipt_line_items_receipt_id'), 'receipt_line_items', ['receipt_id'], unique=False)
    op.create_foreign_key(None, 'receipt_line_items', 'receipts', ['receipt_id'], ['id'])
    op.add_column('receipts', sa.Column('session_id', sa.Uuid(), nullable=True))
    op.add_column('receipts', sa.Column('ocr_status', sa.String(length=20), nullable=False))
    op.add_column('receipts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_receipts_session_id'), 'receipts', ['session_id'], unique=False)
    op.create_foreign_key(None, 'receipts', 'shopping_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_index(op.f('ix_receipts_session_id'), table_name='receipts')
    op.drop_column('receipts', 'created_at')
    op.drop_column('receipts', 'ocr_status')
    op.drop_column('receipts', 'session_id')
    op.drop_constraint(None, 'receipt_line_items', type_='foreignkey')
    op.drop_index(op.f('ix_receipt_line_items_receipt_id'), table_name='receipt_line_items')
    op.drop_column('receipt_line_items', 'created_at')
    op.drop_column('receipt_line_items', 'receipt_id')
    # ### end Alembic commands ###
