"""Declarative base — placeholder. See progress.md → Backend — Core → "SQLAlchemy models"."""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# SQLAlchemy's recommended naming convention — gives every FK/UQ/CK/PK/IX a deterministic
# name so Alembic autogenerate can always reference constraints by name (unnamed constraints
# break autogenerated downgrade()s, which call op.drop_constraint(name, ...)).
convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=convention)
